<select class="filter logic" id="select2">
          <option data-value="">Expertise</option>
          <option data-value="ecommerce">E-commerce</option>
          <option data-value="pm">Product Management</option>
          <option data-value="smarthouse">Smart House</option>
          <option data-value="hardware">Hardware Startup</option>
          <option data-value="startup">Startup</option>
          <option data-value="mmedia">Media</option>
          <option data-value="gaming">Gaming</option>
          <option data-value="tm">Task Management</option>
          <!-- <option data-value="riskam">Risk Assessment management</option> -->
          <option data-value="warehouse">Warehouse</option>
          <option data-value="cashflow">Cashflow</option>
          <option data-value="webcraw">Web Crawling</option>
          <option data-value="militarytrade">Military Trade</option>
          <option data-value="retailtrade">Retail Trade</option>
          <option data-value="logistics">Logistics</option>
          <option data-value="advertisement">Advertisement</option>
          <option data-value="datamining">Data Mining</option>
          <option data-value="erp">ERP</option>
          <option data-value="realestate">Real Estate</option>
          <option data-value="halgorithms">Heuristic Algorithms</option>
          <option data-value="marketing">Marketing</option>
          <option data-value="crm">CRM</option>
          <option data-value="smm">SMM</option>
          <option data-value="locationbased">Location-Based</option>
          <option data-value="prototyping">Prototyping</option>
          <option data-value="recruitment">Recruitment</option>
          <option data-value="hr">HR</option>
          <option data-value="cms">CMS</option>
          <option data-value="socialnetworking">Social Networking</option>
          <option data-value="docflow">Document Flow</option>
          <option data-value="malgorithms">Matching Algorithms</option>
          <option data-value="travel">Travel</option>
          <option data-value="mmalgorithms">Multimedia Algorithms</option>
          <option data-value="chat">Chat</option>
          <option data-value="stocktaking">Stocktaking</option>
          <option data-value="accounting">Accounting</option>
          <option data-value="bpa">Business Process Automation </option>
      </select>