<select class="filter tech" id="select1">
        <option data-value="">Technology</option>
        <option data-value="hlo">Highload optimization</option>
        <option data-value="net">.NET</option>
        <option data-value="design">Design</option>
        <option data-value="html">HTML</option>
        <option data-value="html5">HTML 5</option>
        <option data-value="css">CSS</option>
        <option data-value="less">LESS</option>
        <option data-value="css3">CSS 3</option>
        <option data-value="sass">SASS</option>
        <option data-value="responsive">Responsive layout</option>
        <option data-value="c">C#</option>
        <option data-value="vb">VB.NET</option>
        <option data-value="sql">SQL Server</option>
        <option data-value="mysql">MySql</option>
        <option data-value="php">PHP</option>
        <option data-value="ruby">Ruby on Rail</option>
        <option data-value="postgre">Postgresql</option>
        <option data-value="ios">iOS</option>
        <option data-value="android">Android</option>
        <option data-value="webforms">ASP.NET WebForms</option>
        <option data-value="aspmvc">ASP.NET MVC</option>
        <option data-value="windows">Windows Desktop</option>
        <option data-value="silverlight">Silverlight</option>
        <option data-value="pouch">PouchDB</option>
        <option data-value="bootstrap">Bootstrap</option>
        <option data-value="js">Javascript</option>
        <option data-value="coffee">CoffeeScript</option>
        <option data-value="jquery">jQuery</option>
        <option data-value="google">Google API</option>
        <option data-value="fbapi">Facebook API</option>
        <option data-value="linkedin">LinkedIn API</option>
        <option data-value="twiapi">Twitter API</option>
        <option data-value="razor">Razor</option>
        <option data-value="mvc">ASP.Net MVC 4</option>
        <option data-value="transact">Transact SQL</option>
        <option data-value="vs">Visual Studio</option>
        <option data-value="msaccess">MS Access</option>
        <option data-value="winforms">Win Forms controls</option>
        <option data-value="websockets">WebSockets</option>
        <option data-value="delphi">Delphi</option>
        <option data-value="oracle">Oracle</option>
        <option data-value="flash">Adobe Flash</option>
        <option data-value="vcache">Varnish Cache</option>
        <option data-value="adonet">ADO.NET</option>
        <option data-value="EF">EF</option>
      </select>